/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

/**
 *
 * @author Banjo
 */
public class Nezet extends javax.swing.JFrame {

    /**
     * Creates new form Nezet
     */
    public Nezet() {
        initComponents();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        negyedik = new javax.swing.JPanel();
        nt = new javax.swing.JScrollPane();
        ntext = new javax.swing.JTextArea();
        hatodik = new javax.swing.JPanel();
        ht = new javax.swing.JScrollPane();
        htext = new javax.swing.JTextArea();
        kilencedik = new javax.swing.JPanel();
        kt = new javax.swing.JScrollPane();
        ktext = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Kiralynok");

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        ntext.setColumns(20);
        ntext.setRows(5);
        nt.setViewportView(ntext);

        javax.swing.GroupLayout negyedikLayout = new javax.swing.GroupLayout(negyedik);
        negyedik.setLayout(negyedikLayout);
        negyedikLayout.setHorizontalGroup(
            negyedikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(negyedikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nt)
                .addContainerGap())
        );
        negyedikLayout.setVerticalGroup(
            negyedikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, negyedikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nt, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("4. feladat", negyedik);

        htext.setColumns(20);
        htext.setRows(5);
        ht.setViewportView(htext);

        javax.swing.GroupLayout hatodikLayout = new javax.swing.GroupLayout(hatodik);
        hatodik.setLayout(hatodikLayout);
        hatodikLayout.setHorizontalGroup(
            hatodikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hatodikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ht)
                .addContainerGap())
        );
        hatodikLayout.setVerticalGroup(
            hatodikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hatodikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ht, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("6. feladat", hatodik);

        ktext.setColumns(20);
        ktext.setRows(5);
        kt.setViewportView(ktext);

        javax.swing.GroupLayout kilencedikLayout = new javax.swing.GroupLayout(kilencedik);
        kilencedik.setLayout(kilencedikLayout);
        kilencedikLayout.setHorizontalGroup(
            kilencedikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kilencedikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kt)
                .addContainerGap())
        );
        kilencedikLayout.setVerticalGroup(
            kilencedikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kilencedikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kt, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("9. feladat", kilencedik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        
    }//GEN-LAST:event_jTabbedPane1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nezet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nezet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hatodik;
    private javax.swing.JScrollPane ht;
    private javax.swing.JTextArea htext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel kilencedik;
    private javax.swing.JScrollPane kt;
    private javax.swing.JTextArea ktext;
    private javax.swing.JPanel negyedik;
    private javax.swing.JScrollPane nt;
    private javax.swing.JTextArea ntext;
    // End of variables declaration//GEN-END:variables
}
